name: mage
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - pytorch=2.1.0
  - torchvision=0.16.0
  - numpy=1.19.2
  - pillow=10.0.1
  - pip:
    - albumentations
    - opencv-python
    - pudb
    - imageio
    - imageio-ffmpeg
    - pytorch-lightning
    - omegaconf
    - test-tube>=0.7.5
    - streamlit>=0.73.1
    - einops
    - more-itertools>=8.0.0
    - transformers
    - timm==0.3.2
    - pycocotools
    - -e .